import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/footer"; 
import { AppProvider } from "../context/AppContext";

export const metadata: Metadata = {
  title: "The Insight Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Navbar/>

          <main className="min-h-screen"> 
            {children}
          </main>
         
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}